version: 0.2

phases:
  pre_build:
    commands:
      - mvn clean install
      - ls
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 034362060516.dkr.ecr.ap-south-1.amazonaws.com
      - docker build . -t myspringapp:v1
      - docker images
      - docker tag  myspringapp:v1  034362060516.dkr.ecr.ap-south-1.amazonaws.com/myspringapp:v1
      - docker push 034362060516.dkr.ecr.ap-south-1.amazonaws.com/myspringapp:v1
      
